### ISSUE TITLE
Feature: Projects listed by commit activity

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/WebSiteTwo#2]
It would be interesting to have the page of projects where the project could be ordered, using their commit activity or by using the points burn graph

**Comment by tansaku** [comment]
yes - would be wonderful to have more options - we do currently have them listed at the moment by some function of github activity - however I think we need to split out things that are developer facing from those are charity facing, i.e. be thinking about all these things in terms of our key stakeholders for the site or sites
